import type { Problem } from "../interfaces/Types";

export const problemList: Problem[] = [
  // WEEK 1: Arrays Fundamentals (Easy → Medium progression)
  {
    day: 1,
    week: 1,
    theme: "Arrays & Hashing Basics",
    title: "Two Sum",
    difficulty: "Easy",
    leetcode: 1,
    technique: "Hash Map",
  },
  {
    day: 1,
    week: 1,
    theme: "Arrays & Hashing Basics",
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    leetcode: 121,
    technique: "Single Pass",
  },
  {
    day: 1,
    week: 1,
    theme: "Arrays & Hashing Basics",
    title: "Contains Duplicate",
    difficulty: "Easy",
    leetcode: 217,
    technique: "Hash Set",
  },
  {
    day: 1,
    week: 1,
    theme: "Arrays & Hashing Basics",
    title: "Product of Array Except Self",
    difficulty: "Medium",
    leetcode: 238,
    technique: "Prefix/Suffix",
  },

  {
    day: 2,
    week: 1,
    theme: "Arrays & Hashing Basics",
    title: "Valid Anagram",
    difficulty: "Easy",
    leetcode: 242,
    technique: "Hash Map",
  },
  {
    day: 2,
    week: 1,
    theme: "Arrays & Hashing Basics",
    title: "Group Anagrams",
    difficulty: "Medium",
    leetcode: 49,
    technique: "Hash Map + Sorting",
  },
  {
    day: 2,
    week: 1,
    theme: "Arrays & Hashing Basics",
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    leetcode: 347,
    technique: "Bucket Sort/Heap",
  },
  {
    day: 2,
    week: 1,
    theme: "Arrays & Hashing Basics",
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    leetcode: 128,
    technique: "Hash Set",
  },

  {
    day: 3,
    week: 1,
    theme: "Two Pointers Introduction",
    title: "Valid Palindrome",
    difficulty: "Easy",
    leetcode: 125,
    technique: "Two Pointers",
  },
  {
    day: 3,
    week: 1,
    theme: "Two Pointers Introduction",
    title: "Move Zeroes",
    difficulty: "Easy",
    leetcode: 283,
    technique: "Two Pointers",
  },
  {
    day: 3,
    week: 1,
    theme: "Two Pointers Introduction",
    title: "Container With Most Water",
    difficulty: "Medium",
    leetcode: 11,
    technique: "Two Pointers",
  },
  {
    day: 3,
    week: 1,
    theme: "Two Pointers Introduction",
    title: "3Sum",
    difficulty: "Medium",
    leetcode: 15,
    technique: "Two Pointers + Sort",
  },

  {
    day: 4,
    week: 1,
    theme: "Sliding Window Basics",
    title: "Maximum Average Subarray I",
    difficulty: "Easy",
    leetcode: 643,
    technique: "Fixed Sliding Window",
  },
  {
    day: 4,
    week: 1,
    theme: "Sliding Window Basics",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    leetcode: 3,
    technique: "Variable Sliding Window",
  },
  {
    day: 4,
    week: 1,
    theme: "Sliding Window Basics",
    title: "Minimum Window Substring",
    difficulty: "Hard",
    leetcode: 76,
    technique: "Advanced Sliding Window",
  },

  {
    day: 5,
    week: 1,
    theme: "Array Manipulation",
    title: "Merge Intervals",
    difficulty: "Medium",
    leetcode: 56,
    technique: "Sorting + Merge",
  },
  {
    day: 5,
    week: 1,
    theme: "Array Manipulation",
    title: "Insert Interval",
    difficulty: "Medium",
    leetcode: 57,
    technique: "Linear Scan",
  },
  {
    day: 5,
    week: 1,
    theme: "Array Manipulation",
    title: "Rotate Image",
    difficulty: "Medium",
    leetcode: 48,
    technique: "Matrix Transpose",
  },

  {
    day: 6,
    week: 1,
    theme: "Advanced Arrays",
    title: "Subarray Sum Equals K",
    difficulty: "Medium",
    leetcode: 560,
    technique: "Prefix Sum + Hash",
  },
  {
    day: 6,
    week: 1,
    theme: "Advanced Arrays",
    title: "Continuous Subarray Sum",
    difficulty: "Medium",
    leetcode: 523,
    technique: "Prefix Sum Modulo",
  },
  {
    day: 6,
    week: 1,
    theme: "Advanced Arrays",
    title: "Trapping Rain Water",
    difficulty: "Hard",
    leetcode: 42,
    technique: "Two Pointers/Stack",
  },

  // WEEK 2: More Arrays & String Patterns
  {
    day: 7,
    week: 2,
    theme: "String Manipulation",
    title: "Reverse String",
    difficulty: "Easy",
    leetcode: 344,
    technique: "Two Pointers",
  },
  {
    day: 7,
    week: 2,
    theme: "String Manipulation",
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    leetcode: 5,
    technique: "Expand Around Center",
  },
  {
    day: 7,
    week: 2,
    theme: "String Manipulation",
    title: "Palindromic Substrings",
    difficulty: "Medium",
    leetcode: 647,
    technique: "DP/Expand",
  },
  {
    day: 7,
    week: 2,
    theme: "String Manipulation",
    title: "Longest Palindrome by Concatenating",
    difficulty: "Medium",
    leetcode: 2131,
    technique: "Hash Map + Greedy",
  },

  {
    day: 8,
    week: 2,
    theme: "String Patterns",
    title: "Valid Parentheses",
    difficulty: "Easy",
    leetcode: 20,
    technique: "Stack",
  },
  {
    day: 8,
    week: 2,
    theme: "String Patterns",
    title: "Longest Valid Parentheses",
    difficulty: "Hard",
    leetcode: 32,
    technique: "Stack/DP",
  },
  {
    day: 8,
    week: 2,
    theme: "String Patterns",
    title: "Find All Anagrams in String",
    difficulty: "Medium",
    leetcode: 438,
    technique: "Sliding Window",
  },

  {
    day: 9,
    week: 2,
    theme: "Matrix Problems",
    title: "Spiral Matrix",
    difficulty: "Medium",
    leetcode: 54,
    technique: "Simulation",
  },
  {
    day: 9,
    week: 2,
    theme: "Matrix Problems",
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    leetcode: 73,
    technique: "In-place Marking",
  },
  {
    day: 9,
    week: 2,
    theme: "Matrix Problems",
    title: "Word Search",
    difficulty: "Medium",
    leetcode: 79,
    technique: "Backtracking",
  },

  {
    day: 10,
    week: 2,
    theme: "Array + Hash Advanced",
    title: "Sort Colors",
    difficulty: "Medium",
    leetcode: 75,
    technique: "Dutch National Flag",
  },
  {
    day: 10,
    week: 2,
    theme: "Array + Hash Advanced",
    title: "Majority Element",
    difficulty: "Easy",
    leetcode: 169,
    technique: "Boyer-Moore",
  },
  {
    day: 10,
    week: 2,
    theme: "Array + Hash Advanced",
    title: "First Missing Positive",
    difficulty: "Hard",
    leetcode: 41,
    technique: "Array as Hash",
  },

  {
    day: 11,
    week: 2,
    theme: "Prefix/Suffix Patterns",
    title: "Range Sum Query Immutable",
    difficulty: "Easy",
    leetcode: 303,
    technique: "Prefix Sum",
  },
  {
    day: 11,
    week: 2,
    theme: "Prefix/Suffix Patterns",
    title: "Range Sum Query 2D",
    difficulty: "Medium",
    leetcode: 304,
    technique: "2D Prefix Sum",
  },
  {
    day: 11,
    week: 2,
    theme: "Prefix/Suffix Patterns",
    title: "Maximum Subarray",
    difficulty: "Medium",
    leetcode: 53,
    technique: "Kadane's Algorithm",
  },

  {
    day: 12,
    week: 2,
    theme: "Week 1-2 Mixed Review",
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    leetcode: 424,
    technique: "Sliding Window",
  },
  {
    day: 12,
    week: 2,
    theme: "Week 1-2 Mixed Review",
    title: "Valid Sudoku",
    difficulty: "Medium",
    leetcode: 36,
    technique: "Hash Set",
  },
  {
    day: 12,
    week: 2,
    theme: "Week 1-2 Mixed Review",
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    leetcode: 4,
    technique: "Binary Search",
  },

  // WEEK 3: Binary Search Mastery
  {
    day: 13,
    week: 3,
    theme: "Binary Search Basics",
    title: "Binary Search",
    difficulty: "Easy",
    leetcode: 704,
    technique: "Standard BS",
  },
  {
    day: 13,
    week: 3,
    theme: "Binary Search Basics",
    title: "Search Insert Position",
    difficulty: "Easy",
    leetcode: 35,
    technique: "Lower Bound",
  },
  {
    day: 13,
    week: 3,
    theme: "Binary Search Basics",
    title: "Find Peak Element",
    difficulty: "Medium",
    leetcode: 162,
    technique: "BS on Peaks",
  },
  {
    day: 13,
    week: 3,
    theme: "Binary Search Basics",
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    leetcode: 33,
    technique: "Modified BS",
  },

  {
    day: 14,
    week: 3,
    theme: "BS on Answer",
    title: "Sqrt(x)",
    difficulty: "Easy",
    leetcode: 69,
    technique: "BS on Answer",
  },
  {
    day: 14,
    week: 3,
    theme: "BS on Answer",
    title: "Koko Eating Bananas",
    difficulty: "Medium",
    leetcode: 875,
    technique: "BS on Answer",
  },
  {
    day: 14,
    week: 3,
    theme: "BS on Answer",
    title: "Minimum Number of Days to Make m Bouquets",
    difficulty: "Medium",
    leetcode: 1482,
    technique: "BS on Answer",
  },
  {
    day: 14,
    week: 3,
    theme: "BS on Answer",
    title: "Split Array Largest Sum",
    difficulty: "Hard",
    leetcode: 410,
    technique: "BS on Answer",
  },

  {
    day: 15,
    week: 3,
    theme: "BS Variants",
    title: "Find First and Last Position",
    difficulty: "Medium",
    leetcode: 34,
    technique: "Lower/Upper Bound",
  },
  {
    day: 15,
    week: 3,
    theme: "BS Variants",
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    leetcode: 74,
    technique: "Treat as 1D",
  },
  {
    day: 15,
    week: 3,
    theme: "BS Variants",
    title: "Search a 2D Matrix II",
    difficulty: "Medium",
    leetcode: 240,
    technique: "Staircase Search",
  },

  {
    day: 16,
    week: 3,
    theme: "Advanced BS",
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    leetcode: 153,
    technique: "BS on Rotated",
  },
  {
    day: 16,
    week: 3,
    theme: "Advanced BS",
    title: "Time Based Key-Value Store",
    difficulty: "Medium",
    leetcode: 981,
    technique: "BS + Hash Map",
  },
  {
    day: 16,
    week: 3,
    theme: "Advanced BS",
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    leetcode: 4,
    technique: "BS Partition",
  },

  {
    day: 17,
    week: 3,
    theme: "BS Applications",
    title: "Capacity To Ship Packages Within D Days",
    difficulty: "Medium",
    leetcode: 1011,
    technique: "BS on Answer",
  },
  {
    day: 17,
    week: 3,
    theme: "BS Applications",
    title: "Minimize Max Distance to Gas Station",
    difficulty: "Hard",
    leetcode: 774,
    technique: "BS on Answer",
  },
  {
    day: 17,
    week: 3,
    theme: "BS Applications",
    title: "Aggressive Cows (GFG)",
    difficulty: "Hard",
    leetcode: "GFG",
    technique: "BS on Answer",
  },

  {
    day: 18,
    week: 3,
    theme: "BS Review",
    title: "Single Element in Sorted Array",
    difficulty: "Medium",
    leetcode: 540,
    technique: "BS on Pairs",
  },
  {
    day: 18,
    week: 3,
    theme: "BS Review",
    title: "Find K Closest Elements",
    difficulty: "Medium",
    leetcode: 658,
    technique: "BS + Sliding Window",
  },
  {
    day: 18,
    week: 3,
    theme: "BS Review",
    title: "Count of Smaller Numbers After Self",
    difficulty: "Hard",
    leetcode: 315,
    technique: "Merge Sort/BIT",
  },

  // WEEK 4: Linked Lists & Stacks
  {
    day: 19,
    week: 4,
    theme: "Linked List Basics",
    title: "Reverse Linked List",
    difficulty: "Easy",
    leetcode: 206,
    technique: "Iterative/Recursive",
  },
  {
    day: 19,
    week: 4,
    theme: "Linked List Basics",
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    leetcode: 21,
    technique: "Two Pointers",
  },
  {
    day: 19,
    week: 4,
    theme: "Linked List Basics",
    title: "Remove Nth Node From End",
    difficulty: "Medium",
    leetcode: 19,
    technique: "Fast/Slow Pointers",
  },
  {
    day: 19,
    week: 4,
    theme: "Linked List Basics",
    title: "Reorder List",
    difficulty: "Medium",
    leetcode: 143,
    technique: "Find Mid + Reverse + Merge",
  },

  {
    day: 20,
    week: 4,
    theme: "Linked List Advanced",
    title: "Linked List Cycle",
    difficulty: "Easy",
    leetcode: 141,
    technique: "Fast/Slow Pointers",
  },
  {
    day: 20,
    week: 4,
    theme: "Linked List Advanced",
    title: "Add Two Numbers",
    difficulty: "Medium",
    leetcode: 2,
    technique: "Simulation",
  },
  {
    day: 20,
    week: 4,
    theme: "Linked List Advanced",
    title: "Copy List with Random Pointer",
    difficulty: "Medium",
    leetcode: 138,
    technique: "Hash Map/Interleave",
  },
  {
    day: 20,
    week: 4,
    theme: "Linked List Advanced",
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    leetcode: 23,
    technique: "Min Heap",
  },

  {
    day: 21,
    week: 4,
    theme: "Stack Basics",
    title: "Min Stack",
    difficulty: "Medium",
    leetcode: 155,
    technique: "Auxiliary Stack",
  },
  {
    day: 21,
    week: 4,
    theme: "Stack Basics",
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    leetcode: 150,
    technique: "Stack",
  },
  {
    day: 21,
    week: 4,
    theme: "Stack Basics",
    title: "Basic Calculator II",
    difficulty: "Medium",
    leetcode: 227,
    technique: "Stack",
  },

  {
    day: 22,
    week: 4,
    theme: "Monotonic Stack",
    title: "Next Greater Element I",
    difficulty: "Easy",
    leetcode: 496,
    technique: "Monotonic Stack",
  },
  {
    day: 22,
    week: 4,
    theme: "Monotonic Stack",
    title: "Daily Temperatures",
    difficulty: "Medium",
    leetcode: 739,
    technique: "Monotonic Stack",
  },
  {
    day: 22,
    week: 4,
    theme: "Monotonic Stack",
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    leetcode: 84,
    technique: "Monotonic Stack",
  },

  {
    day: 23,
    week: 4,
    theme: "Stack Applications",
    title: "Decode String",
    difficulty: "Medium",
    leetcode: 394,
    technique: "Stack",
  },
  {
    day: 23,
    week: 4,
    theme: "Stack Applications",
    title: "Asteroid Collision",
    difficulty: "Medium",
    leetcode: 735,
    technique: "Stack Simulation",
  },
  {
    day: 23,
    week: 4,
    theme: "Stack Applications",
    title: "Basic Calculator",
    difficulty: "Hard",
    leetcode: 224,
    technique: "Stack with Signs",
  },

  {
    day: 24,
    week: 4,
    theme: "Design Problems",
    title: "Implement Queue using Stacks",
    difficulty: "Easy",
    leetcode: 232,
    technique: "Two Stacks",
  },
  {
    day: 24,
    week: 4,
    theme: "Design Problems",
    title: "LRU Cache",
    difficulty: "Medium",
    leetcode: 146,
    technique: "Hash Map + DLL",
  },
  {
    day: 24,
    week: 4,
    theme: "Design Problems",
    title: "LFU Cache",
    difficulty: "Hard",
    leetcode: 460,
    technique: "Hash Map + DLL + Freq Map",
  },

  // WEEK 5: Trees Foundation
  {
    day: 25,
    week: 5,
    theme: "Tree Traversal",
    title: "Binary Tree Inorder Traversal",
    difficulty: "Easy",
    leetcode: 94,
    technique: "DFS/Stack",
  },
  {
    day: 25,
    week: 5,
    theme: "Tree Traversal",
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    leetcode: 102,
    technique: "BFS",
  },
  {
    day: 25,
    week: 5,
    theme: "Tree Traversal",
    title: "Binary Tree Zigzag Level Order",
    difficulty: "Medium",
    leetcode: 103,
    technique: "BFS + Flag",
  },
  {
    day: 25,
    week: 5,
    theme: "Tree Traversal",
    title: "Vertical Order Traversal",
    difficulty: "Hard",
    leetcode: 987,
    technique: "BFS + Coordinates",
  },

  {
    day: 26,
    week: 5,
    theme: "Tree Properties",
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    leetcode: 104,
    technique: "DFS",
  },
  {
    day: 26,
    week: 5,
    theme: "Tree Properties",
    title: "Diameter of Binary Tree",
    difficulty: "Easy",
    leetcode: 543,
    technique: "DFS + Global Max",
  },
  {
    day: 26,
    week: 5,
    theme: "Tree Properties",
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    leetcode: 110,
    technique: "DFS Height Check",
  },
  {
    day: 26,
    week: 5,
    theme: "Tree Properties",
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    leetcode: 124,
    technique: "DFS + Global Max",
  },

  {
    day: 27,
    week: 5,
    theme: "Tree Construction",
    title: "Invert Binary Tree",
    difficulty: "Easy",
    leetcode: 226,
    technique: "DFS Swap",
  },
  {
    day: 27,
    week: 5,
    theme: "Tree Construction",
    title: "Construct Binary Tree from Preorder and Inorder",
    difficulty: "Medium",
    leetcode: 105,
    technique: "Recursion + Hash Map",
  },
  {
    day: 27,
    week: 5,
    theme: "Tree Construction",
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard",
    leetcode: 297,
    technique: "DFS/BFS Encoding",
  },

  {
    day: 28,
    week: 5,
    theme: "BST",
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    leetcode: 98,
    technique: "DFS Range Check",
  },
  {
    day: 28,
    week: 5,
    theme: "BST",
    title: "Kth Smallest Element in BST",
    difficulty: "Medium",
    leetcode: 230,
    technique: "Inorder Traversal",
  },
  {
    day: 28,
    week: 5,
    theme: "BST",
    title: "Lowest Common Ancestor of BST",
    difficulty: "Medium",
    leetcode: 235,
    technique: "BST Property",
  },

  {
    day: 29,
    week: 5,
    theme: "Advanced Trees",
    title: "Same Tree",
    difficulty: "Easy",
    leetcode: 100,
    technique: "DFS Comparison",
  },
  {
    day: 29,
    week: 5,
    theme: "Advanced Trees",
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    leetcode: 572,
    technique: "DFS",
  },
  {
    day: 29,
    week: 5,
    theme: "Advanced Trees",
    title: "Lowest Common Ancestor of Binary Tree",
    difficulty: "Medium",
    leetcode: 236,
    technique: "DFS",
  },
  {
    day: 29,
    week: 5,
    theme: "Advanced Trees",
    title: "Binary Tree Cameras",
    difficulty: "Hard",
    leetcode: 968,
    technique: "Greedy DFS",
  },

  {
    day: 30,
    week: 5,
    theme: "Tree Review",
    title: "Count Good Nodes in Binary Tree",
    difficulty: "Medium",
    leetcode: 1448,
    technique: "DFS + Max Tracker",
  },
  {
    day: 30,
    week: 5,
    theme: "Tree Review",
    title: "Binary Tree Right Side View",
    difficulty: "Medium",
    leetcode: 199,
    technique: "BFS/DFS",
  },
  {
    day: 30,
    week: 5,
    theme: "Tree Review",
    title: "All Nodes Distance K",
    difficulty: "Medium",
    leetcode: 863,
    technique: "Graph Conversion + BFS",
  },

  // WEEK 6: Graphs Foundation
  {
    day: 31,
    week: 6,
    theme: "Graph Basics",
    title: "Number of Islands",
    difficulty: "Medium",
    leetcode: 200,
    technique: "DFS/BFS/Union-Find",
  },
  {
    day: 31,
    week: 6,
    theme: "Graph Basics",
    title: "Clone Graph",
    difficulty: "Medium",
    leetcode: 133,
    technique: "DFS/BFS + Hash Map",
  },
  {
    day: 31,
    week: 6,
    theme: "Graph Basics",
    title: "Max Area of Island",
    difficulty: "Medium",
    leetcode: 695,
    technique: "DFS",
  },

  {
    day: 32,
    week: 6,
    theme: "Graph Traversal",
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    leetcode: 417,
    technique: "Multi-source DFS",
  },
  {
    day: 32,
    week: 6,
    theme: "Graph Traversal",
    title: "Surrounded Regions",
    difficulty: "Medium",
    leetcode: 130,
    technique: "DFS from Border",
  },
  {
    day: 32,
    week: 6,
    theme: "Graph Traversal",
    title: "Word Search II",
    difficulty: "Hard",
    leetcode: 212,
    technique: "Trie + Backtracking",
  },

  {
    day: 33,
    week: 6,
    theme: "BFS Applications",
    title: "Rotting Oranges",
    difficulty: "Medium",
    leetcode: 994,
    technique: "Multi-source BFS",
  },
  {
    day: 33,
    week: 6,
    theme: "BFS Applications",
    title: "01 Matrix",
    difficulty: "Medium",
    leetcode: 542,
    technique: "Multi-source BFS",
  },
  {
    day: 33,
    week: 6,
    theme: "BFS Applications",
    title: "Shortest Path in Binary Matrix",
    difficulty: "Medium",
    leetcode: 1091,
    technique: "BFS",
  },

  {
    day: 34,
    week: 6,
    theme: "Topological Sort",
    title: "Course Schedule",
    difficulty: "Medium",
    leetcode: 207,
    technique: "Topological Sort",
  },
  {
    day: 34,
    week: 6,
    theme: "Topological Sort",
    title: "Course Schedule II",
    difficulty: "Medium",
    leetcode: 210,
    technique: "Topological Sort",
  },
  {
    day: 34,
    week: 6,
    theme: "Topological Sort",
    title: "Alien Dictionary",
    difficulty: "Hard",
    leetcode: 269,
    technique: "Topo Sort + Graph Build",
  },

  {
    day: 35,
    week: 6,
    theme: "Union Find",
    title: "Redundant Connection",
    difficulty: "Medium",
    leetcode: 684,
    technique: "Union-Find",
  },
  {
    day: 35,
    week: 6,
    theme: "Union Find",
    title: "Accounts Merge",
    difficulty: "Medium",
    leetcode: 721,
    technique: "Union-Find",
  },
  {
    day: 35,
    week: 6,
    theme: "Union Find",
    title: "Number of Islands II",
    difficulty: "Hard",
    leetcode: 305,
    technique: "Union-Find",
  },

  {
    day: 36,
    week: 6,
    theme: "Advanced Graphs",
    title: "Word Ladder",
    difficulty: "Hard",
    leetcode: 127,
    technique: "BFS Shortest Path",
  },
  {
    day: 36,
    week: 6,
    theme: "Advanced Graphs",
    title: "Minimum Height Trees",
    difficulty: "Medium",
    leetcode: 310,
    technique: "Topological Sort",
  },
  {
    day: 36,
    week: 6,
    theme: "Advanced Graphs",
    title: "Swim in Rising Water",
    difficulty: "Hard",
    leetcode: 778,
    technique: "Binary Search + BFS",
  },

  // WEEK 7: Heap & Priority Queue
  {
    day: 37,
    week: 7,
    theme: "Heap Basics",
    title: "Kth Largest Element in Array",
    difficulty: "Medium",
    leetcode: 215,
    technique: "Min Heap",
  },
  {
    day: 37,
    week: 7,
    theme: "Heap Basics",
    title: "Last Stone Weight",
    difficulty: "Easy",
    leetcode: 1046,
    technique: "Max Heap",
  },
  {
    day: 37,
    week: 7,
    theme: "Heap Basics",
    title: "K Closest Points to Origin",
    difficulty: "Medium",
    leetcode: 973,
    technique: "Max Heap",
  },
  {
    day: 37,
    week: 7,
    theme: "Heap Basics",
    title: "Find Median from Data Stream",
    difficulty: "Hard",
    leetcode: 295,
    technique: "Two Heaps",
  },

  {
    day: 38,
    week: 7,
    theme: "Heap Applications",
    title: "Task Scheduler",
    difficulty: "Medium",
    leetcode: 621,
    technique: "Max Heap + Queue",
  },
  {
    day: 38,
    week: 7,
    theme: "Heap Applications",
    title: "Reorganize String",
    difficulty: "Medium",
    leetcode: 767,
    technique: "Max Heap",
  },
  {
    day: 38,
    week: 7,
    theme: "Heap Applications",
    title: "Rearrange String k Distance Apart",
    difficulty: "Hard",
    leetcode: 358,
    technique: "Max Heap + Queue",
  },

  {
    day: 39,
    week: 7,
    theme: "Advanced Heap",
    title: "Kth Smallest Element in Sorted Matrix",
    difficulty: "Medium",
    leetcode: 378,
    technique: "Min Heap",
  },
  {
    day: 39,
    week: 7,
    theme: "Advanced Heap",
    title: "Meeting Rooms II",
    difficulty: "Medium",
    leetcode: 253,
    technique: "Min Heap",
  },
  {
    day: 39,
    week: 7,
    theme: "Advanced Heap",
    title: "Sliding Window Median",
    difficulty: "Hard",
    leetcode: 480,
    technique: "Two Heaps",
  },

  {
    day: 40,
    week: 7,
    theme: "Greedy + Heap",
    title: "Meeting Rooms",
    difficulty: "Easy",
    leetcode: 252,
    technique: "Sorting",
  },
  {
    day: 40,
    week: 7,
    theme: "Greedy + Heap",
    title: "Non-overlapping Intervals",
    difficulty: "Medium",
    leetcode: 435,
    technique: "Greedy Sorting",
  },
  {
    day: 40,
    week: 7,
    theme: "Greedy + Heap",
    title: "Minimum Interval to Include Each Query",
    difficulty: "Hard",
    leetcode: 1851,
    technique: "Heap + Sort",
  },

  {
    day: 41,
    week: 7,
    theme: "Mixed Review",
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    leetcode: 239,
    technique: "Deque",
  },
  {
    day: 41,
    week: 7,
    theme: "Mixed Review",
    title: "Cheapest Flights Within K Stops",
    difficulty: "Medium",
    leetcode: 787,
    technique: "BFS/Dijkstra",
  },
  {
    day: 41,
    week: 7,
    theme: "Mixed Review",
    title: "Network Delay Time",
    difficulty: "Medium",
    leetcode: 743,
    technique: "Dijkstra",
  },

  {
    day: 42,
    week: 7,
    theme: "Week 7 Consolidation",
    title: "IPO",
    difficulty: "Hard",
    leetcode: 502,
    technique: "Two Heaps",
  },
  {
    day: 42,
    week: 7,
    theme: "Week 7 Consolidation",
    title: "The Skyline Problem",
    difficulty: "Hard",
    leetcode: 218,
    technique: "Heap/Sweep Line",
  },
  {
    day: 42,
    week: 7,
    theme: "Week 7 Consolidation",
    title: "Maximum Performance of a Team",
    difficulty: "Hard",
    leetcode: 1383,
    technique: "Heap + Greedy",
  },

  // WEEK 8: Backtracking & Recursion
  {
    day: 43,
    week: 8,
    theme: "Backtracking Intro",
    title: "Subsets",
    difficulty: "Medium",
    leetcode: 78,
    technique: "Backtracking",
  },
  {
    day: 43,
    week: 8,
    theme: "Backtracking Intro",
    title: "Subsets II",
    difficulty: "Medium",
    leetcode: 90,
    technique: "Backtracking + Skip Duplicates",
  },
  {
    day: 43,
    week: 8,
    theme: "Backtracking Intro",
    title: "Permutations",
    difficulty: "Medium",
    leetcode: 46,
    technique: "Backtracking",
  },

  {
    day: 44,
    week: 8,
    theme: "Combinations",
    title: "Combinations",
    difficulty: "Medium",
    leetcode: 77,
    technique: "Backtracking",
  },
  {
    day: 44,
    week: 8,
    theme: "Combinations",
    title: "Combination Sum",
    difficulty: "Medium",
    leetcode: 39,
    technique: "Backtracking",
  },
  {
    day: 44,
    week: 8,
    theme: "Combinations",
    title: "Combination Sum II",
    difficulty: "Medium",
    leetcode: 40,
    technique: "Backtracking + Skip",
  },
  {
    day: 44,
    week: 8,
    theme: "Combinations",
    title: "Combination Sum III",
    difficulty: "Medium",
    leetcode: 216,
    technique: "Backtracking",
  },

  {
    day: 45,
    week: 8,
    theme: "String Backtracking",
    title: "Letter Combinations of Phone Number",
    difficulty: "Medium",
    leetcode: 17,
    technique: "Backtracking",
  },
  {
    day: 45,
    week: 8,
    theme: "String Backtracking",
    title: "Generate Parentheses",
    difficulty: "Medium",
    leetcode: 22,
    technique: "Backtracking",
  },
  {
    day: 45,
    week: 8,
    theme: "String Backtracking",
    title: "Palindrome Partitioning",
    difficulty: "Medium",
    leetcode: 131,
    technique: "Backtracking + DP",
  },

  {
    day: 46,
    week: 8,
    theme: "Advanced Backtracking",
    title: "N-Queens",
    difficulty: "Hard",
    leetcode: 51,
    technique: "Backtracking",
  },
  {
    day: 46,
    week: 8,
    theme: "Advanced Backtracking",
    title: "Sudoku Solver",
    difficulty: "Hard",
    leetcode: 37,
    technique: "Backtracking",
  },
  {
    day: 46,
    week: 8,
    theme: "Advanced Backtracking",
    title: "Expression Add Operators",
    difficulty: "Hard",
    leetcode: 282,
    technique: "Backtracking",
  },

  {
    day: 47,
    week: 8,
    theme: "Recursion Patterns",
    title: "Letter Case Permutation",
    difficulty: "Medium",
    leetcode: 784,
    technique: "Recursion",
  },
  {
    day: 47,
    week: 8,
    theme: "Recursion Patterns",
    title: "Beautiful Arrangement",
    difficulty: "Medium",
    leetcode: 526,
    technique: "Backtracking",
  },
  {
    day: 47,
    week: 8,
    theme: "Recursion Patterns",
    title: "Word Break II",
    difficulty: "Hard",
    leetcode: 140,
    technique: "Backtracking + Memo",
  },

  {
    day: 48,
    week: 8,
    theme: "Week 8 Review",
    title: "Restore IP Addresses",
    difficulty: "Medium",
    leetcode: 93,
    technique: "Backtracking",
  },
  {
    day: 48,
    week: 8,
    theme: "Week 8 Review",
    title: "Word Search",
    difficulty: "Medium",
    leetcode: 79,
    technique: "Backtracking",
  },
  {
    day: 48,
    week: 8,
    theme: "Week 8 Review",
    title: "Remove Invalid Parentheses",
    difficulty: "Hard",
    leetcode: 301,
    technique: "BFS/Backtracking",
  },

  // WEEK 9: Dynamic Programming Foundation
  {
    day: 49,
    week: 9,
    theme: "1D DP Basics",
    title: "Climbing Stairs",
    difficulty: "Easy",
    leetcode: 70,
    technique: "1D DP",
  },
  {
    day: 49,
    week: 9,
    theme: "1D DP Basics",
    title: "Min Cost Climbing Stairs",
    difficulty: "Easy",
    leetcode: 746,
    technique: "1D DP",
  },
  {
    day: 49,
    week: 9,
    theme: "1D DP Basics",
    title: "House Robber",
    difficulty: "Medium",
    leetcode: 198,
    technique: "1D DP",
  },
  {
    day: 49,
    week: 9,
    theme: "1D DP Basics",
    title: "House Robber II",
    difficulty: "Medium",
    leetcode: 213,
    technique: "1D DP Circular",
  },

  {
    day: 50,
    week: 9,
    theme: "2D DP Grid",
    title: "Unique Paths",
    difficulty: "Medium",
    leetcode: 62,
    technique: "2D DP",
  },
  {
    day: 50,
    week: 9,
    theme: "2D DP Grid",
    title: "Unique Paths II",
    difficulty: "Medium",
    leetcode: 63,
    technique: "2D DP",
  },
  {
    day: 50,
    week: 9,
    theme: "2D DP Grid",
    title: "Minimum Path Sum",
    difficulty: "Medium",
    leetcode: 64,
    technique: "2D DP",
  },
  {
    day: 50,
    week: 9,
    theme: "2D DP Grid",
    title: "Dungeon Game",
    difficulty: "Hard",
    leetcode: 174,
    technique: "Reverse DP",
  },

  {
    day: 51,
    week: 9,
    theme: "LIS Pattern",
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    leetcode: 300,
    technique: "DP + Binary Search",
  },
  {
    day: 51,
    week: 9,
    theme: "LIS Pattern",
    title: "Longest Increasing Path in Matrix",
    difficulty: "Hard",
    leetcode: 329,
    technique: "DFS + Memo",
  },
  {
    day: 51,
    week: 9,
    theme: "LIS Pattern",
    title: "Russian Doll Envelopes",
    difficulty: "Hard",
    leetcode: 354,
    technique: "Sort + LIS",
  },

  {
    day: 52,
    week: 9,
    theme: "String DP",
    title: "Longest Common Subsequence",
    difficulty: "Medium",
    leetcode: 1143,
    technique: "2D DP",
  },
  {
    day: 52,
    week: 9,
    theme: "String DP",
    title: "Edit Distance",
    difficulty: "Medium",
    leetcode: 72,
    technique: "2D DP",
  },
  {
    day: 52,
    week: 9,
    theme: "String DP",
    title: "Distinct Subsequences",
    difficulty: "Hard",
    leetcode: 115,
    technique: "2D DP",
  },

  {
    day: 53,
    week: 9,
    theme: "Knapsack Pattern",
    title: "Partition Equal Subset Sum",
    difficulty: "Medium",
    leetcode: 416,
    technique: "0/1 Knapsack",
  },
  {
    day: 53,
    week: 9,
    theme: "Knapsack Pattern",
    title: "Target Sum",
    difficulty: "Medium",
    leetcode: 494,
    technique: "0/1 Knapsack",
  },
  {
    day: 53,
    week: 9,
    theme: "Knapsack Pattern",
    title: "Ones and Zeroes",
    difficulty: "Medium",
    leetcode: 474,
    technique: "2D Knapsack",
  },

  {
    day: 54,
    week: 9,
    theme: "Unbounded DP",
    title: "Coin Change",
    difficulty: "Medium",
    leetcode: 322,
    technique: "Unbounded Knapsack",
  },
  {
    day: 54,
    week: 9,
    theme: "Unbounded DP",
    title: "Coin Change II",
    difficulty: "Medium",
    leetcode: 518,
    technique: "Unbounded Knapsack",
  },
  {
    day: 54,
    week: 9,
    theme: "Unbounded DP",
    title: "Perfect Squares",
    difficulty: "Medium",
    leetcode: 279,
    technique: "Unbounded Knapsack",
  },

  // WEEK 10: Advanced DP
  {
    day: 55,
    week: 10,
    theme: "Palindrome DP",
    title: "Longest Palindromic Subsequence",
    difficulty: "Medium",
    leetcode: 516,
    technique: "2D DP",
  },
  {
    day: 55,
    week: 10,
    theme: "Palindrome DP",
    title: "Palindromic Substrings",
    difficulty: "Medium",
    leetcode: 647,
    technique: "Expand/DP",
  },
  {
    day: 55,
    week: 10,
    theme: "Palindrome DP",
    title: "Palindrome Partitioning II",
    difficulty: "Hard",
    leetcode: 132,
    technique: "DP",
  },

  {
    day: 56,
    week: 10,
    theme: "Word Break Pattern",
    title: "Word Break",
    difficulty: "Medium",
    leetcode: 139,
    technique: "DP + Hash",
  },
  {
    day: 56,
    week: 10,
    theme: "Word Break Pattern",
    title: "Word Break II",
    difficulty: "Hard",
    leetcode: 140,
    technique: "Backtracking + Memo",
  },
  {
    day: 56,
    week: 10,
    theme: "Word Break Pattern",
    title: "Concatenated Words",
    difficulty: "Hard",
    leetcode: 472,
    technique: "DP + Trie",
  },

  {
    day: 57,
    week: 10,
    theme: "State Machine DP",
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    leetcode: 121,
    technique: "State Machine",
  },
  {
    day: 57,
    week: 10,
    theme: "State Machine DP",
    title: "Best Time to Buy and Sell Stock with Cooldown",
    difficulty: "Medium",
    leetcode: 309,
    technique: "State Machine",
  },
  {
    day: 57,
    week: 10,
    theme: "State Machine DP",
    title: "Best Time to Buy and Sell Stock IV",
    difficulty: "Hard",
    leetcode: 188,
    technique: "State Machine",
  },

  {
    day: 58,
    week: 10,
    theme: "Interval DP",
    title: "Decode Ways",
    difficulty: "Medium",
    leetcode: 91,
    technique: "1D DP",
  },
  {
    day: 58,
    week: 10,
    theme: "Interval DP",
    title: "Decode Ways II",
    difficulty: "Hard",
    leetcode: 639,
    technique: "1D DP",
  },
  {
    day: 58,
    week: 10,
    theme: "Interval DP",
    title: "Burst Balloons",
    difficulty: "Hard",
    leetcode: 312,
    technique: "Interval DP",
  },

  {
    day: 59,
    week: 10,
    theme: "Advanced DP",
    title: "Maximal Square",
    difficulty: "Medium",
    leetcode: 221,
    technique: "2D DP",
  },
  {
    day: 59,
    week: 10,
    theme: "Advanced DP",
    title: "Maximal Rectangle",
    difficulty: "Hard",
    leetcode: 85,
    technique: "Histogram DP",
  },
  {
    day: 59,
    week: 10,
    theme: "Advanced DP",
    title: "Count Square Submatrices",
    difficulty: "Medium",
    leetcode: 1277,
    technique: "2D DP",
  },

  {
    day: 60,
    week: 10,
    theme: "DP Review",
    title: "Regular Expression Matching",
    difficulty: "Hard",
    leetcode: 10,
    technique: "2D DP",
  },
  {
    day: 60,
    week: 10,
    theme: "DP Review",
    title: "Wildcard Matching",
    difficulty: "Hard",
    leetcode: 44,
    technique: "2D DP",
  },
  {
    day: 60,
    week: 10,
    theme: "DP Review",
    title: "Interleaving String",
    difficulty: "Hard",
    leetcode: 97,
    technique: "2D DP",
  },

  // WEEK 11: Tries, Bit Manipulation & Math
  {
    day: 61,
    week: 11,
    theme: "Trie Basics",
    title: "Implement Trie",
    difficulty: "Medium",
    leetcode: 208,
    technique: "Trie",
  },
  {
    day: 61,
    week: 11,
    theme: "Trie Basics",
    title: "Design Add and Search Words",
    difficulty: "Medium",
    leetcode: 211,
    technique: "Trie + DFS",
  },
  {
    day: 61,
    week: 11,
    theme: "Trie Basics",
    title: "Word Search II",
    difficulty: "Hard",
    leetcode: 212,
    technique: "Trie + Backtrack",
  },

  {
    day: 62,
    week: 11,
    theme: "Bit Manipulation",
    title: "Single Number",
    difficulty: "Easy",
    leetcode: 136,
    technique: "XOR",
  },
  {
    day: 62,
    week: 11,
    theme: "Bit Manipulation",
    title: "Number of 1 Bits",
    difficulty: "Easy",
    leetcode: 191,
    technique: "Bit Count",
  },
  {
    day: 62,
    week: 11,
    theme: "Bit Manipulation",
    title: "Counting Bits",
    difficulty: "Easy",
    leetcode: 338,
    technique: "DP + Bits",
  },
  {
    day: 62,
    week: 11,
    theme: "Bit Manipulation",
    title: "Maximum XOR of Two Numbers",
    difficulty: "Medium",
    leetcode: 421,
    technique: "Trie",
  },

  {
    day: 63,
    week: 11,
    theme: "Advanced Bits",
    title: "Reverse Bits",
    difficulty: "Easy",
    leetcode: 190,
    technique: "Bit Manipulation",
  },
  {
    day: 63,
    week: 11,
    theme: "Advanced Bits",
    title: "Sum of Two Integers",
    difficulty: "Medium",
    leetcode: 371,
    technique: "Bit Manipulation",
  },
  {
    day: 63,
    week: 11,
    theme: "Advanced Bits",
    title: "Bitwise AND of Numbers Range",
    difficulty: "Medium",
    leetcode: 201,
    technique: "Bit Manipulation",
  },

  {
    day: 64,
    week: 11,
    theme: "Math Problems",
    title: "Pow(x, n)",
    difficulty: "Medium",
    leetcode: 50,
    technique: "Fast Exponentiation",
  },
  {
    day: 64,
    week: 11,
    theme: "Math Problems",
    title: "Multiply Strings",
    difficulty: "Medium",
    leetcode: 43,
    technique: "String Math",
  },
  {
    day: 64,
    week: 11,
    theme: "Math Problems",
    title: "Integer to English Words",
    difficulty: "Hard",
    leetcode: 273,
    technique: "String Conversion",
  },

  {
    day: 65,
    week: 11,
    theme: "Number Theory",
    title: "Happy Number",
    difficulty: "Easy",
    leetcode: 202,
    technique: "Cycle Detection",
  },
  {
    day: 65,
    week: 11,
    theme: "Number Theory",
    title: "Factorial Trailing Zeroes",
    difficulty: "Medium",
    leetcode: 172,
    technique: "Math",
  },
  {
    day: 65,
    week: 11,
    theme: "Number Theory",
    title: "Count Primes",
    difficulty: "Medium",
    leetcode: 204,
    technique: "Sieve of Eratosthenes",
  },

  {
    day: 66,
    week: 11,
    theme: "Week 11 Review",
    title: "Maximum Product of Word Lengths",
    difficulty: "Medium",
    leetcode: 318,
    technique: "Bit Manipulation",
  },
  {
    day: 66,
    week: 11,
    theme: "Week 11 Review",
    title: "UTF-8 Validation",
    difficulty: "Medium",
    leetcode: 393,
    technique: "Bit Manipulation",
  },
  {
    day: 66,
    week: 11,
    theme: "Week 11 Review",
    title: "Max Points on a Line",
    difficulty: "Hard",
    leetcode: 149,
    technique: "Hash Map + Math",
  },

  // WEEK 12: Mixed Google Favorites (TRUE RANDOMIZATION BEGINS)
  {
    day: 67,
    week: 12,
    theme: "Design Problems",
    title: "Insert Delete GetRandom O(1)",
    difficulty: "Medium",
    leetcode: 380,
    technique: "Hash + Array",
  },
  {
    day: 67,
    week: 12,
    theme: "Design Problems",
    title: "Design Twitter",
    difficulty: "Medium",
    leetcode: 355,
    technique: "Hash + Heap",
  },
  {
    day: 67,
    week: 12,
    theme: "Design Problems",
    title: "Design In-Memory File System",
    difficulty: "Hard",
    leetcode: 588,
    technique: "Trie + Map",
  },

  {
    day: 68,
    week: 12,
    theme: "Random Sampling",
    title: "Random Pick with Weight",
    difficulty: "Medium",
    leetcode: 528,
    technique: "Prefix Sum + BS",
  },
  {
    day: 68,
    week: 12,
    theme: "Random Sampling",
    title: "Random Pick Index",
    difficulty: "Medium",
    leetcode: 398,
    technique: "Reservoir Sampling",
  },
  {
    day: 68,
    week: 12,
    theme: "Random Sampling",
    title: "Random Point in Non-overlapping Rectangles",
    difficulty: "Medium",
    leetcode: 497,
    technique: "Prefix Sum",
  },

  {
    day: 69,
    week: 12,
    theme: "Advanced String",
    title: "Shortest Palindrome",
    difficulty: "Hard",
    leetcode: 214,
    technique: "KMP",
  },
  {
    day: 69,
    week: 12,
    theme: "Advanced String",
    title: "Minimum Window Subsequence",
    difficulty: "Hard",
    leetcode: 727,
    technique: "Two Pointers/DP",
  },
  {
    day: 69,
    week: 12,
    theme: "Advanced String",
    title: "Text Justification",
    difficulty: "Hard",
    leetcode: 68,
    technique: "Simulation",
  },

  {
    day: 70,
    week: 12,
    theme: "Complex Simulation",
    title: "Next Permutation",
    difficulty: "Medium",
    leetcode: 31,
    technique: "Array Manipulation",
  },
  {
    day: 70,
    week: 12,
    theme: "Complex Simulation",
    title: "Rotate Array",
    difficulty: "Medium",
    leetcode: 189,
    technique: "Reverse",
  },
  {
    day: 70,
    week: 12,
    theme: "Complex Simulation",
    title: "Jump Game II",
    difficulty: "Medium",
    leetcode: 45,
    technique: "Greedy",
  },

  {
    day: 71,
    week: 12,
    theme: "Google Special",
    title: "Longest Substring with At Most K Distinct Characters",
    difficulty: "Medium",
    leetcode: 340,
    technique: "Sliding Window",
  },
  {
    day: 71,
    week: 12,
    theme: "Google Special",
    title: "Read N Characters Given Read4 II",
    difficulty: "Hard",
    leetcode: 158,
    technique: "Simulation",
  },
  {
    day: 71,
    week: 12,
    theme: "Google Special",
    title: "Minimum Cost to Hire K Workers",
    difficulty: "Hard",
    leetcode: 857,
    technique: "Heap + Greedy",
  },

  {
    day: 72,
    week: 12,
    theme: "Week 12 Finale",
    title: "Reconstruct Itinerary",
    difficulty: "Hard",
    leetcode: 332,
    technique: "Eulerian Path",
  },
  {
    day: 72,
    week: 12,
    theme: "Week 12 Finale",
    title: "Alien Dictionary",
    difficulty: "Hard",
    leetcode: 269,
    technique: "Topological Sort",
  },
  {
    day: 72,
    week: 12,
    theme: "Week 12 Finale",
    title: "Trapping Rain Water II",
    difficulty: "Hard",
    leetcode: 407,
    technique: "Heap + BFS",
  },

  // WEEK 13: Advanced DP & State Machines (Days 73-78)
  {
    day: 73,
    week: 13,
    theme: "DP on Trees",
    title: "House Robber III",
    difficulty: "Medium",
    leetcode: 337,
    technique: "Tree DP",
  },
  {
    day: 73,
    week: 13,
    theme: "DP on Trees",
    title: "Binary Tree Cameras",
    difficulty: "Hard",
    leetcode: 968,
    technique: "Tree DP + Greedy",
  },
  {
    day: 73,
    week: 13,
    theme: "DP on Trees",
    title: "Distribute Coins in Binary Tree",
    difficulty: "Medium",
    leetcode: 979,
    technique: "Post-order DP",
  },
  {
    day: 73,
    week: 13,
    theme: "DP on Trees",
    title: "Longest Path With Different Adjacent Characters",
    difficulty: "Hard",
    leetcode: 2246,
    technique: "Tree DP",
  },

  {
    day: 74,
    week: 13,
    theme: "State Machine DP",
    title: "Best Time to Buy/Sell Stock with Transaction Fee",
    difficulty: "Medium",
    leetcode: 714,
    technique: "State Machine",
  },
  {
    day: 74,
    week: 13,
    theme: "State Machine DP",
    title: "Best Time to Buy/Sell Stock with Cooldown",
    difficulty: "Medium",
    leetcode: 309,
    technique: "State Machine",
  },
  {
    day: 74,
    week: 13,
    theme: "State Machine DP",
    title: "Best Time to Buy/Sell Stock IV",
    difficulty: "Hard",
    leetcode: 188,
    technique: "State Machine",
  },

  {
    day: 75,
    week: 13,
    theme: "Bitmask DP",
    title: "Partition to K Equal Sum Subsets",
    difficulty: "Medium",
    leetcode: 698,
    technique: "Bitmask DP",
  },
  {
    day: 75,
    week: 13,
    theme: "Bitmask DP",
    title: "Smallest Sufficient Team",
    difficulty: "Hard",
    leetcode: 1125,
    technique: "Bitmask DP",
  },
  {
    day: 75,
    week: 13,
    theme: "Bitmask DP",
    title: "Number of Ways to Wear Different Hats",
    difficulty: "Hard",
    leetcode: 1434,
    technique: "Bitmask DP",
  },

  {
    day: 76,
    week: 13,
    theme: "Interval DP",
    title: "Stone Game",
    difficulty: "Medium",
    leetcode: 877,
    technique: "Interval DP",
  },
  {
    day: 76,
    week: 13,
    theme: "Interval DP",
    title: "Stone Game II",
    difficulty: "Medium",
    leetcode: 1140,
    technique: "Interval DP",
  },
  {
    day: 76,
    week: 13,
    theme: "Interval DP",
    title: "Stone Game III",
    difficulty: "Hard",
    leetcode: 1406,
    technique: "Interval DP",
  },
  {
    day: 76,
    week: 13,
    theme: "Interval DP",
    title: "Stone Game IV",
    difficulty: "Hard",
    leetcode: 1510,
    technique: "DP",
  },

  {
    day: 77,
    week: 13,
    theme: "Advanced String DP",
    title: "Shortest Common Supersequence",
    difficulty: "Hard",
    leetcode: 1092,
    technique: "DP + Reconstruction",
  },
  {
    day: 77,
    week: 13,
    theme: "Advanced String DP",
    title: "Distinct Subsequences II",
    difficulty: "Hard",
    leetcode: 940,
    technique: "DP + Last Occurrence",
  },
  {
    day: 77,
    week: 13,
    theme: "Advanced String DP",
    title: "Minimum Insertion Steps to Make String Palindrome",
    difficulty: "Hard",
    leetcode: 1312,
    technique: "DP",
  },

  {
    day: 78,
    week: 13,
    theme: "DP Optimization",
    title: "Maximum Profit in Job Scheduling",
    difficulty: "Hard",
    leetcode: 1235,
    technique: "DP + Binary Search",
  },
  {
    day: 78,
    week: 13,
    theme: "DP Optimization",
    title: "Maximum Number of Events That Can Be Attended II",
    difficulty: "Hard",
    leetcode: 1751,
    technique: "DP + Binary Search",
  },
  {
    day: 78,
    week: 13,
    theme: "DP Optimization",
    title: "Painting the Walls",
    difficulty: "Hard",
    leetcode: 2742,
    technique: "Knapsack DP",
  },

  // WEEK 14: Graph Algorithms & Advanced Patterns (Days 79-84)
  {
    day: 79,
    week: 14,
    theme: "Shortest Path Variations",
    title: "Network Delay Time",
    difficulty: "Medium",
    leetcode: 743,
    technique: "Dijkstra",
  },
  {
    day: 79,
    week: 14,
    theme: "Shortest Path Variations",
    title: "Cheapest Flights Within K Stops",
    difficulty: "Medium",
    leetcode: 787,
    technique: "Bellman-Ford/BFS",
  },
  {
    day: 79,
    week: 14,
    theme: "Shortest Path Variations",
    title: "Find the City With Smallest Number of Neighbors",
    difficulty: "Medium",
    leetcode: 1334,
    technique: "Floyd-Warshall",
  },
  {
    day: 79,
    week: 14,
    theme: "Shortest Path Variations",
    title: "Minimum Time to Visit Disappearing Nodes",
    difficulty: "Hard",
    leetcode: 3203,
    technique: "Modified Dijkstra",
  },

  {
    day: 80,
    week: 14,
    theme: "Minimum Spanning Tree",
    title: "Min Cost to Connect All Points",
    difficulty: "Medium",
    leetcode: 1584,
    technique: "Prim's/Kruskal's",
  },
  {
    day: 80,
    week: 14,
    theme: "Minimum Spanning Tree",
    title: "Connecting Cities With Minimum Cost",
    difficulty: "Medium",
    leetcode: 1135,
    technique: "MST",
  },
  {
    day: 80,
    week: 14,
    theme: "Minimum Spanning Tree",
    title: "Optimize Water Distribution",
    difficulty: "Hard",
    leetcode: 1168,
    technique: "MST + Virtual Node",
  },

  {
    day: 81,
    week: 14,
    theme: "Eulerian Path/Circuit",
    title: "Reconstruct Itinerary",
    difficulty: "Hard",
    leetcode: 332,
    technique: "Eulerian Path",
  },
  {
    day: 81,
    week: 14,
    theme: "Eulerian Path/Circuit",
    title: "Cracking the Safe",
    difficulty: "Hard",
    leetcode: 753,
    technique: "De Bruijn Sequence",
  },
  {
    day: 81,
    week: 14,
    theme: "Eulerian Path/Circuit",
    title: "Valid Arrangement of Pairs",
    difficulty: "Hard",
    leetcode: 2097,
    technique: "Eulerian Path",
  },

  {
    day: 82,
    week: 14,
    theme: "Bipartite & Matching",
    title: "Is Graph Bipartite?",
    difficulty: "Medium",
    leetcode: 785,
    technique: "BFS/DFS Coloring",
  },
  {
    day: 82,
    week: 14,
    theme: "Bipartite & Matching",
    title: "Maximum Students Taking Exam",
    difficulty: "Hard",
    leetcode: 1349,
    technique: "Bipartite Matching",
  },
  {
    day: 82,
    week: 14,
    theme: "Bipartite & Matching",
    title: "Minimum Number of Days to Disconnect Island",
    difficulty: "Hard",
    leetcode: 1568,
    technique: "Articulation Points",
  },

  {
    day: 83,
    week: 14,
    theme: "Advanced Union-Find",
    title: "Number of Provinces",
    difficulty: "Medium",
    leetcode: 547,
    technique: "Union-Find",
  },
  {
    day: 83,
    week: 14,
    theme: "Advanced Union-Find",
    title: "Swim in Rising Water",
    difficulty: "Hard",
    leetcode: 778,
    technique: "Union-Find + Binary Search",
  },
  {
    day: 83,
    week: 14,
    theme: "Advanced Union-Find",
    title: "Last Day Where You Can Still Cross",
    difficulty: "Hard",
    leetcode: 1970,
    technique: "Union-Find + Reverse Time",
  },

  {
    day: 84,
    week: 14,
    theme: "Graph Connectivity",
    title: "Critical Connections in a Network",
    difficulty: "Hard",
    leetcode: 1192,
    technique: "Tarjan's Algorithm",
  },
  {
    day: 84,
    week: 14,
    theme: "Graph Connectivity",
    title: "Find Critical and Pseudo-Critical Edges",
    difficulty: "Hard",
    leetcode: 1489,
    technique: "MST + Bridge Detection",
  },
  {
    day: 84,
    week: 14,
    theme: "Graph Connectivity",
    title: "Minimum Degree of a Connected Trio in a Graph",
    difficulty: "Hard",
    leetcode: 1761,
    technique: "Graph Theory",
  },

  // WEEK 15: Google-Specific Patterns & System Design (Days 85-90)
  {
    day: 85,
    week: 15,
    theme: "Random & Sampling",
    title: "Random Pick with Weight",
    difficulty: "Medium",
    leetcode: 528,
    technique: "Prefix Sum + Binary Search",
  },
  {
    day: 85,
    week: 15,
    theme: "Random & Sampling",
    title: "Random Pick Index",
    difficulty: "Medium",
    leetcode: 398,
    technique: "Reservoir Sampling",
  },
  {
    day: 85,
    week: 15,
    theme: "Random & Sampling",
    title: "Generate Random Point in a Circle",
    difficulty: "Medium",
    leetcode: 478,
    technique: "Rejection Sampling",
  },
  {
    day: 85,
    week: 15,
    theme: "Random & Sampling",
    title: "Random Flip Matrix",
    difficulty: "Medium",
    leetcode: 519,
    technique: "Hash Map + Swap",
  },

  {
    day: 86,
    week: 15,
    theme: "Geometry & Math",
    title: "Max Points on a Line",
    difficulty: "Hard",
    leetcode: 149,
    technique: "Slope + Hash Map",
  },
  {
    day: 86,
    week: 15,
    theme: "Geometry & Math",
    title: "Valid Square",
    difficulty: "Medium",
    leetcode: 593,
    technique: "Geometry",
  },
  {
    day: 86,
    week: 15,
    theme: "Geometry & Math",
    title: "Erect the Fence",
    difficulty: "Hard",
    leetcode: 587,
    technique: "Convex Hull",
  },
  {
    day: 86,
    week: 15,
    theme: "Geometry & Math",
    title: "Minimum Area Rectangle",
    difficulty: "Medium",
    leetcode: 939,
    technique: "Diagonal Points",
  },

  {
    day: 87,
    week: 15,
    theme: "Design Data Structures",
    title: "LRU Cache",
    difficulty: "Medium",
    leetcode: 146,
    technique: "Hash Map + Doubly Linked List",
  },
  {
    day: 87,
    week: 15,
    theme: "Design Data Structures",
    title: "LFU Cache",
    difficulty: "Hard",
    leetcode: 460,
    technique: "Hash Maps + Linked Lists",
  },
  {
    day: 87,
    week: 15,
    theme: "Design Data Structures",
    title: "Time Based Key-Value Store",
    difficulty: "Medium",
    leetcode: 981,
    technique: "Hash Map + Binary Search",
  },
  {
    day: 87,
    week: 15,
    theme: "Design Data Structures",
    title: "Snapshot Array",
    difficulty: "Medium",
    leetcode: 1146,
    technique: "Binary Search",
  },

  {
    day: 88,
    week: 15,
    theme: "Advanced System Design",
    title: "Design Twitter",
    difficulty: "Medium",
    leetcode: 355,
    technique: "OOD + Heap",
  },
  {
    day: 88,
    week: 15,
    theme: "Advanced System Design",
    title: "Design Search Autocomplete System",
    difficulty: "Hard",
    leetcode: 642,
    technique: "Trie + Heap",
  },
  {
    day: 88,
    week: 15,
    theme: "Advanced System Design",
    title: "Design Browser History",
    difficulty: "Medium",
    leetcode: 1472,
    technique: "Two Stacks/Array",
  },
  {
    day: 88,
    week: 15,
    theme: "Advanced System Design",
    title: "Design File System",
    difficulty: "Medium",
    leetcode: 1166,
    technique: "Trie/Hash Map",
  },

  {
    day: 89,
    week: 15,
    theme: "Google Classic Problems",
    title: "Fruit Into Baskets",
    difficulty: "Medium",
    leetcode: 904,
    technique: "Sliding Window",
  },
  {
    day: 89,
    week: 15,
    theme: "Google Classic Problems",
    title: "Longest Substring with At Most K Distinct Characters",
    difficulty: "Medium",
    leetcode: 340,
    technique: "Sliding Window",
  },
  {
    day: 89,
    week: 15,
    theme: "Google Classic Problems",
    title: "Odd Even Jump",
    difficulty: "Hard",
    leetcode: 975,
    technique: "DP + Tree Map",
  },
  {
    day: 89,
    week: 15,
    theme: "Google Classic Problems",
    title: "Robot Room Cleaner",
    difficulty: "Hard",
    leetcode: 489,
    technique: "DFS + Backtracking",
  },

  {
    day: 90,
    week: 15,
    theme: "Final Review & Meta Problems",
    title: "First Missing Positive",
    difficulty: "Hard",
    leetcode: 41,
    technique: "Array as Hash Map",
  },
  {
    day: 90,
    week: 15,
    theme: "Final Review & Meta Problems",
    title: "Trapping Rain Water",
    difficulty: "Hard",
    leetcode: 42,
    technique: "Two Pointers",
  },
  {
    day: 90,
    week: 15,
    theme: "Final Review & Meta Problems",
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    leetcode: 4,
    technique: "Binary Search",
  },
  {
    day: 90,
    week: 15,
    theme: "Final Review & Meta Problems",
    title: "Regular Expression Matching",
    difficulty: "Hard",
    leetcode: 10,
    technique: "DP",
  },
];
